# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# See https://docs.npmjs.com/trusted-publishers

name: Publish to NPM
on:
  push:
    tags:
      - "**@*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for OIDC

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: echo "pkg_name=${GITHUB_REF_NAME##*@}" >> "$GITHUB_ENV"
      - run: echo "pkg_version=${GITHUB_REF_NAME%@*}" >> "$GITHUB_ENV"
      - name: Generate types
        run: node --run types:generate
      - name: Publish $pkg_name $pkg_version with provenance
        run: npm publish --workspace="packages/$pkg_name"
